mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=pimpannt
    - MYSQL_PASSWORD=ThePassword
    - MYSQL_DATABASE=cbdMember
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"