pring:
  main:
    web-environment: false

  datasource:
    url: jdbc:mysql://localhost:3306;databaseName=db_example
    username: pimpan
    password: ThePassword
    tomcat:
      initial-size: 4
      max-active: 200
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl